### ISSUE TITLE
SSID Regex causes Catastrophic backtracking infinite loop

### ISSUE THREAD

**Issue by giorgio-zamparelli** [msolters/wifi-control-node#11]
The Regular Expressions used to parse the airport -I on Mac OS X causes the "Catastrophic backtracking" which with long SSID (ex. "Fruit Tree Lodge & Coffee Shop") will cause an (almost) infinite loop that will freeze the V8 and node with a bug that will not be logged or transmitted.
The number of loops to parse the SSID is exponential on the number of characters so it does not occur with SSID with shorter names.
You can try this on the following website:
https://regex101.com/r/cY3wI8/1
Where this is the regex new RegExp(/(._)+: (._)+/); and the string is "SSID: Fruit Tree Lodge & Coffee Shop"

**Comment by giorgio-zamparelli** [comment]
Fixed this by removing the + from the regex expression `/(.*)+: (.*)+/` becomes `/(.*): (.*)/`

changed wifi-control.js line 34 to : 

```
switch (process.platform) {
    case "linux":
      parsePatterns.nmcli_line = new RegExp(/([^:]):\s+(.*)/);
      break;
    case "win32":
      parsePatterns.netsh_line = new RegExp(/([^:]): (.*)/);
      break;
    case "darwin":
      AirPort = "/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport";
      parsePatterns.airport_line = new RegExp(/(.*): (.*)/);

}
```

**Comment by msolters** [comment]
Yes, I noticed this myself.  I fixed it already in commit https://github.com/msolters/wifi-control-node/commit/361f703e7ab370f0fd33c9fe7ad26669ef74942b.  However, I have not released a new version to NPM.

I don't think there is a functional difference between our two solutions.  (Please correct me if I am wrong.)

Please note as well that, for this project, the `.coffee` file must be changed.  The `.js` file is autocompiled from that source, so I make a rule of not merging anything manually into the JS.
