### ISSUE TITLE
Confirmation timeout error (Windows)

### ISSUE THREAD

**Issue by danieltrolezi** [msolters/wifi-control-node#18]
Hi!

The package isn't working correctly on Windows.
When I try to connect to a WiFi, I get this error: Connection confirmation timed out. (5000ms).

The weird thing though, that even with this error, the connection is stablished.
I'm calling `getIfaceState()` in the `connectToAP()` callback and I get this:

```
{
  msg: "Successfully acquired state of network interface wlan.",
  power: true,
  ssid: "...",
  success: true
}
```

**Comment by bergaminrafael** [comment]
Any luck solving this? I'm having the same problem.

@danieltrolezi are you on win10 or win7?
